cmake_minimum_required(VERSION 3.21)
project(ScopeBridge VERSION 1.2.7 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTORCC ON)
find_package(Qt6 REQUIRED COMPONENTS Core Widgets Svg)
include(FetchContent)
set(QLEMENTINE_SANDBOX OFF CACHE BOOL "" FORCE)
set(QLEMENTINE_SHOWCASE OFF CACHE BOOL "" FORCE)
FetchContent_Declare(qlementine
    URL https://api.github.com/repos/oclero/qlementine/tarball/13f72eb8b53bafd9ac24e5562d8ddc28d5440469
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_MakeAvailable(qlementine)
qt_add_executable(ScopeBridge WIN32 main.cpp resources.qrc)
target_compile_definitions(ScopeBridge PRIVATE SCOPEBRIDGE_VERSION="${PROJECT_VERSION}")
target_link_libraries(ScopeBridge PRIVATE Qt6::Core Qt6::Widgets qlementine)
